#!/bin/bash

source /home/amr/.bashrc

WEBSERVER_PATH=$(dirname $0)

cat $WEBSERVER_PATH/log/log.txt | grep -q "setValue: Problem" || echo "restoring DB";rm -rf $WEBSERVER_PATH/Library/Database;mv $WEBSERVER_PATH/Library/Database$(date "+%u") $WEBSERVER_PATH/Library/Database

