#!/bin/bash

source /home/amr/.bashrc

WEBSERVER_PATH=$(dirname $0)

cd ${WEBSERVER_PATH}

SERVER_PS=$(sudo lsof -i :9001 | grep TCP | head -n 1 | awk '{print $2}')
if [ ! -z "$SERVER_PS" ]; then
    sudo kill -9 $SERVER_PS
fi

echo "Running DarkEye"

Database_PATH=${WEBSERVER_PATH}/Library/Database
mkdir -p ${Database_PATH}
mkdir -p ${WEBSERVER_PATH}/log

cp ${WEBSERVER_PATH}/log/log.txt ${WEBSERVER_PATH}/log/log$(date "+%u").txt

swift run Run serve --hostname 0.0.0.0 --port 9001 > ${WEBSERVER_PATH}/log/log.txt 2>&1 &

disown
sleep 2
cat ${WEBSERVER_PATH}/log/log.txt
