#!/bin/bash

source /home/amr/.bashrc

WEBSERVER_PATH=$(dirname $0)

./callStop
./update all

cd ${WEBSERVER_PATH}

sleep 5
./stop

echo "Running DarkEye_dev"

Database_PATH=${WEBSERVER_PATH}/Library/Database
mkdir -p ${Database_PATH}
mkdir -p ${WEBSERVER_PATH}/log

cp ${WEBSERVER_PATH}/log/log.txt ${WEBSERVER_PATH}/log/log$(date "+%u").txt

swift run Run serve --hostname 0.0.0.0 --port 8091 > ${WEBSERVER_PATH}/log/log.txt 2>&1 &
python ${WEBSERVER_PATH}/python/downloadLinks.py > ${WEBSERVER_PATH}/log/plog.txt 2>&1 &

disown
sleep 3
cat ${WEBSERVER_PATH}/log/log.txt
