#!/bin/bash

echo "Stopping Darkeye"


rm stop.*
wget http://127.0.0.1:9001/darkeye/stop

sleep 7

sudo lsof -i :9001 | grep TCP | awk '{print $2}' | xargs -I{} sudo kill -9 {}
sudo lsof -i :9001 | grep TCP | awk '{print $2}' | xargs -I{} sudo kill -9 {}
sudo lsof -i :9001 | grep TCP | awk '{print $2}' | xargs -I{} sudo kill -9 {}

# in macOS, run:
# sudo lsof -i :8080 | grep TCP | awk '{print $2}' | xargs -I{} sudo kill -9 {}
