#!/bin/bash

echo "Updating HaneinWebserver_dev"

git pull
git commit -a -m "Update from server"
git push
if [ "$1" == "full" ]; then
    echo "Making full update by running swift package update"
    swift package update
fi
 
