#!/bin/bash

echo "Updating DarkEye"

git pull
git checkout main
git pull
git checkout release
git merge main --no-edit
git commit -a -m "Update from server"
git push
if [ "$1" == "all" ]; then
    echo
    echo "Updating all packages by running swift package update"
    swift package update
fi

